[project]
name = "avro-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastavro>=1.10.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
